"""
Email Sender for UK Port Shipping PDF Report
Uses Python's smtplib with SMTP_SSL for Gmail.
"""

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime


def send_report_email(
    sender_email: str,
    sender_password: str,
    recipient_email: str,
    pdf_path: str,
    week_ending: str = "",
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 465,
) -> dict:
    """
    Send the PDF shipping report via email.

    Args:
        sender_email: Gmail address of the sender
        sender_password: Gmail App Password (not your normal password)
        recipient_email: Recipient email address (or comma-separated list)
        pdf_path: Absolute path to the generated PDF
        week_ending: Week ending date string for subject line
        smtp_host: SMTP server (default: Gmail)
        smtp_port: SMTP port (default: 465 for SSL)

    Returns:
        {"success": True} or {"success": False, "error": str}

    NOTE: For Gmail, you must enable 2-factor authentication and create
    an App Password at https://myaccount.google.com/apppasswords
    """
    try:
        if not os.path.exists(pdf_path):
            return {"success": False, "error": f"PDF not found at: {pdf_path}"}

        subject = f"🚢 UK Port Shipping Report — Week ending {week_ending or datetime.now().strftime('%d %b %Y')}"

        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; background:#f3f4f6; padding:20px;">
          <div style="max-width:600px; margin:auto; background:#fff; border-radius:12px; overflow:hidden; box-shadow:0 4px 24px rgba(0,0,0,0.08);">
            <!-- Header -->
            <div style="background:#0F2A5C; padding:32px 24px; text-align:center;">
              <h1 style="color:#fff; margin:0; font-size:24px;">🚢 UK Port Shipping Intelligence</h1>
              <p style="color:#94A3B8; margin:8px 0 0 0; font-size:14px;">
                Weekly Analysis Report • {week_ending or datetime.now().strftime('%d %B %Y')}
              </p>
            </div>
            <!-- Body -->
            <div style="padding:32px 24px;">
              <p style="color:#374151; font-size:15px; line-height:1.7;">
                Dear Shipping Analyst,
              </p>
              <p style="color:#374151; font-size:15px; line-height:1.7;">
                Your automated <strong>UK Port Shipping Intelligence Report</strong> has been generated
                and is attached to this email as a PDF.
              </p>
              <div style="background:#F0FDF4; border-left:4px solid #22C55E; padding:16px; border-radius:4px; margin:20px 0;">
                <p style="margin:0; color:#166534; font-size:14px;">
                  <strong>📊 Report Includes:</strong><br>
                  ✅ Current week shipping summary for all major UK ports<br>
                  ✅ Week-on-week comparison and trend analysis<br>
                  ✅ ML-predicted next week shipping counts<br>
                  ✅ Highest and lowest traffic port rankings<br>
                  ✅ Model performance metrics (MAE, RMSE, R²)
                </p>
              </div>
              <p style="color:#374151; font-size:15px; line-height:1.7;">
                Please find the full report in the attached PDF. You can also view live predictions
                on the interactive dashboard.
              </p>
              <div style="text-align:center; margin:28px 0;">
                <a href="#" style="background:#0D9488; color:#fff; padding:14px 32px;
                   border-radius:8px; text-decoration:none; font-weight:bold; font-size:15px;">
                  View Dashboard →
                </a>
              </div>
            </div>
            <!-- Footer -->
            <div style="background:#F9FAFB; padding:16px 24px; text-align:center;
                        border-top:1px solid #E5E7EB;">
              <p style="color:#9CA3AF; font-size:12px; margin:0;">
                This report was automatically generated by UK Shipping Analytics Dashboard.<br>
                Generated on {datetime.now().strftime('%d %B %Y at %H:%M')}
              </p>
            </div>
          </div>
        </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = sender_email
        msg["To"] = recipient_email

        msg.attach(MIMEText(html_body, "html"))

        # Attach PDF
        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        filename = os.path.basename(pdf_path)
        part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
        msg.attach(part)

        # Send
        with smtplib.SMTP_SSL(smtp_host, smtp_port) as server:
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, recipient_email.split(","), msg.as_string())

        print(f"✅ Email sent to {recipient_email}")
        return {"success": True, "recipient": recipient_email}

    except Exception as e:
        print(f"❌ Email failed: {e}")
        return {"success": False, "error": str(e)}
